name: gsoc-ds-rl-sql-injection-itinnovation
channels:
  - defaults
  - pytorch
dependencies:
  - autopep8
  - Cython
  - matplotlib
  - notebook
  - pandas
  - pip
  - python=3.9
  - pytorch::pytorch
  - scipy
  - pip:
    - azureml-core
    - gym
    - libinjection-python
    - sqlparse
    - python-dotenv
    - tensorboardX
    - termcolor
    - waf-brain
    - ray[rllib]
    - transformers
    - sentence_transformers
